import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const TRANSLATIONS = {
    en: {
        'nav.home': 'Home',
        'nav.about': 'About',
        'nav.brands': 'Brands',
        'nav.products': 'Products',
        'nav.gallery': 'Gallery',
        'nav.services': 'Services',
        'nav.contact': 'Contact',
        'gallery.title': 'Gallery',
        'gallery.subtitle': 'Work snapshots from Monastir',
        'gallery.description': 'Images and videos documenting our latest refits, coatings, and marina services.',
        'gallery.filterAll': 'All',
        'gallery.filterImages': 'Images',
        'gallery.filterVideos': 'Videos',
        'gallery.empty': 'No gallery entries match that filter.',
        'hero.title': 'Marine Supplies & Services in Monastir',
        'hero.subtitle': 'Quick repairs and full projects: antifouling, polishing, gelcoat, deck renewal, hauling & more.',
        'hero.cta1': 'Explore Services',
        'hero.cta2': 'Get a Quote',
        'about.title': 'About SOFRACOM',
        'brands.title': 'Trusted Brands',
        'brands.subtitle': 'We stock leading marine brands and can quickly order what’s not on-hand via established suppliers.',
        'services.title': 'Services',
        'monoA.title': 'Monastir, Tunisia',
        'monoA.subtitle': 'Marina views • Ribat • Old town',
        'monoB.title': 'Haul-out near Port de pêche',
        'monoB.subtitle': '1 mile from Monastir Marina',
        'testimonials.title': 'What skippers say',
        'faq.title': 'FAQ',
        'faq.q1': 'Do you deliver to the marina?',
        'faq.a1': 'Yes, we’re nearby and can arrange quick deliveries to Marina Monastir.',
        'faq.q2': 'Can I request a free quote?',
        'faq.a2': 'Absolutely. Use the contact form below or call us to discuss your project.',
        'faq.q3': 'Do you stock everything shown?',
        'faq.a3': 'Not all items are in stock at all times, but we can order quickly via suppliers.',
        'contact.title': 'Contact Us',
        'contact.address1': 'SOFRACOM Store',
        'contact.address2': 'Remada Street, Monastir, Tunisia',
        'contact.hours': 'Hours: Mon–Sat, 8:00–17:00 (Closed public holidays)',
        'contact.btn': 'Request a Free Quote',
        'form.name': 'Name',
        'form.email': 'Email',
        'form.subject': 'Subject',
        'form.message': 'Message',
        'form.send': 'Send',
        'footer.quick': 'Quick Links',
        'footer.monastir': 'Near Marina Monastir & Port de pêche',
        'products.catalogBadge': 'SOFRACOM Catalog',
        'products.catalogHeading': 'Explore categories & products',
        'products.catalogCopy': 'Browse the latest antifouling systems, sealants, oils, batteries, and hardware supplied from Monastir.',
        'products.searchPlaceholder': 'Search products…',
        'products.filters.allBrands': 'All brands',
        'products.filters.reset': 'Reset filters',
        'products.card.viewAction': 'View',
        'product.detailLabel': 'Product detail',
        'product.detailBreadcrumbCatalog': 'Catalog',
        'product.detailOnOrder': 'This item is on order; delivery will take longer.',
        'product.detailReadMore': 'Read more',
        'product.detailShowLess': 'Show less',
        'product.datasheet': 'Download datasheet',
        'product.addToCart': 'Add to cart',
        'review.sectionTitle': 'Customer reviews',
        'review.sectionSubtitle': 'Feedback on this product',
        'review.reviewsLabel': 'reviews',
        'review.noReviews': 'No reviews yet.',
        'review.writeTitle': 'Leave a review',
        'review.youPurchased': 'Thank you for purchasing—share your thoughts.',
        'review.onlyBuyers': 'Only verified buyers can leave a review.',
        'review.signInToReview': 'Sign in to leave feedback.',
        'review.ratingLabel': 'Your rating',
        'review.commentLabel': 'Feedback',
        'review.commentPlaceholder': 'Share your experience with this product…',
        'review.submitting': 'Submitting…',
        'review.submitReview': 'Submit review',
        'review.updateReview': 'Update review',
        'review.thankYou': 'Thanks for the feedback!',
        'review.submitFailed': 'Unable to submit your review.',
        'review.mustPurchase': 'You need to purchase this product before reviewing.',
        'review.commentRequired': 'Please add a comment.',
        'cart.fabLabel': 'Cart',
        'cart.title': 'Your order',
        'cart.subtitle': 'Review items then confirm your details.',
        'cart.onOrderTitle': 'On-demand items',
        'cart.onOrderDescription': 'Some items will take longer to arrive—expect a delay until they reach the store.',
        'cart.empty': 'Your cart is empty.',
        'cart.summary.items': 'Items total',
        'cart.summary.delivery': 'Delivery fee',
        'cart.summary.grand': 'Grand total',
        'checkout.title': 'Checkout',
        'checkout.action': 'Checkout',
        'checkout.savedAddressLabel': 'Saved address',
        'checkout.enterNewAddress': 'Enter new address',
        'checkout.deliveryAddressLabel': 'Delivery address',
        'checkout.notesLabel': 'Notes (optional)',
        'checkout.cartEmpty': 'Cart is empty',
        'checkout.missingInfo': 'Name, phone, and address are required.',
        'checkout.sending': 'Sending order…',
        'checkout.orderButton': 'Order',
        'order.confirmation.delayedTitle': 'Order received – delays expected',
        'order.confirmation.delayedSubtitle': 'Order received but may have some delay until on-order items are present in the store.',
        'order.confirmation.successTitle': 'Order received',
        'order.confirmation.successSubtitle': 'Order received successfully.',
        'buttons.goHome': 'Go to home',
        'checkout.signInRequired': 'Sign in to proceed to checkout.',
        'account.label': 'Account',
        'account.mainTitle': 'Manage your profile & orders',
        'account.subtitle': 'Stay signed in, save addresses, and track every purchase from Monastir.',
        'account.welcomeBack': 'Welcome back',
        'account.yourProfile': 'Your profile',
        'account.profileSubtitle': 'Keep your profile in sync for faster checkouts.',
        'account.signOut': 'Sign out',
        'account.savedAddresses': 'Saved addresses',
        'account.orders': 'Orders',
        'account.lastOrder': 'Last order',
        'account.highlights': 'Account highlights',
        'account.statsTip': 'Use saved addresses and order history to reorder faster.',
        'account.defaultAddress': 'Default address',
        'account.phoneLabel': 'Phone',
        'account.accountCreated': 'Account created',
        'account.phoneNotSaved': 'Not saved',
        'account.address': 'address',
        'account.addresses': 'addresses',
        'account.addressLabel': 'Label',
        'account.labelPlaceholder': 'e.g., Marina home',
        'account.addressField': 'Address',
        'account.addressPlaceholder': 'Delivery address',
        'account.saveAddress': 'Save address',
        'account.saveFirstAddress': 'Save your first address to speed up checkout.',
        'account.addressRequired': 'Add an address before saving.',
        'account.addressSaved': 'Address saved.',
        'account.addressSaveFailed': 'Unable to save address.',
        'account.addressRemoved': 'Address removed.',
        'account.addressRemoveFailed': 'Unable to remove address.',
        'account.badgeDefault': 'Default',
        'account.badgeSaved': 'Saved',
        'account.setDefault': 'Set default',
        'account.remove': 'Remove',
        'account.noDefaultAddress': 'No default yet',
        'account.notesPrefix': 'Notes:',
        'account.orderHistory': 'Order history',
        'account.refresh': 'Refresh',
        'account.refreshingProfile': 'Refreshing profile…',
        'account.loadingOrders': 'Loading orders…',
        'account.noOrders': 'No orders yet.',
        'orderStatus.new': 'New',
        'orderStatus.waiting': 'Waiting',
        'orderStatus.in_progress': 'In progress',
        'orderStatus.treated': 'Treated',
        'orderStatus.declined': 'Declined',
        'account.itemsSingular': 'item',
        'account.itemsPlural': 'items',
        'account.signingIn': 'Signing in…',
        'account.signInSuccess': 'Signed in! Redirecting…',
        'account.signInFailed': 'Unable to sign in.',
        'account.returningCustomer': 'Returning customer',
        'account.signInTitle': 'Sign in',
        'account.signInButton': 'Sign in',
        'account.email': 'Email',
        'account.password': 'Password',
        'account.signUpSubtitle': 'New to SOFRACOM',
        'account.signUpTitle': 'Create an account',
        'account.name': 'Name',
        'account.phoneNumber': 'Phone',
        'account.signUpButton': 'Create account',
        'account.passwordMinChars': 'Password must be at least 6 characters.',
        'account.creatingAccount': 'Creating account…',
        'account.accountCreatedSuccess': 'Account created. Welcome!',
        'account.signUpFailed': 'Unable to create account.',
        'account.defaultAddressUpdated': 'Default address updated.',
        'account.defaultAddressUpdateFailed': 'Unable to update default address.',
        'orders.detailsTitle': 'Order summary',
        'orders.timelineLabel': 'Status timeline',
        'orders.itemsLabel': 'Items',
        'orders.addressLabel': 'Delivery address',
        'orders.totalLabel': 'Order total',
        'orders.showDetails': 'Show details',
        'orders.hideDetails': 'Hide details',
        'orders.noItems': 'No items recorded.',
        'orders.itemOpenProduct': 'Open product',
        'orders.itemLeaveReview': 'Leave a review',
        'orders.itemUnavailable': 'Product link unavailable',
    },
    fr: {
        'nav.home': 'Accueil',
        'nav.about': 'À propos',
        'nav.brands': 'Marques',
        'nav.products': 'Produits',
        'nav.gallery': 'Galerie',
        'nav.services': 'Services',
        'nav.contact': 'Contact',
        'gallery.title': 'Galerie',
        'gallery.subtitle': 'Instants de nos travaux',
        'gallery.description': 'Images et vidéos des derniers chantiers, peintures et interventions à Monastir.',
        'gallery.filterAll': 'Tous',
        'gallery.filterImages': 'Images',
        'gallery.filterVideos': 'Vidéos',
        'gallery.empty': 'Aucun contenu disponible pour ce filtre.',
        'hero.title': 'Fournitures et services marins à Monastir',
        'hero.subtitle': 'Petites réparations et projets complets : antifouling, polissage, gelcoat, pont, carénage et plus.',
        'hero.cta1': 'Découvrir les services',
        'hero.cta2': 'Demander un devis',
        'about.title': 'À propos de SOFRACOM',
        'brands.title': 'Marques de confiance',
        'brands.subtitle': 'Nous stockons des marques marines leaders et pouvons commander rapidement ce qui manque.',
        'services.title': 'Services',
        'monoA.title': 'Monastir, Tunisie',
        'monoA.subtitle': 'Vue marina • Ribat • Médina',
        'monoB.title': 'Carénage près du Port de pêche',
        'monoB.subtitle': 'À 1 mile de la Marina de Monastir',
        'testimonials.title': 'Avis de skippers',
        'faq.title': 'FAQ',
        'faq.q1': 'Livrez-vous à la marina ?',
        'faq.a1': 'Oui, nous sommes proches et pouvons livrer rapidement à la Marina de Monastir.',
        'faq.q2': 'Puis-je demander un devis gratuit ?',
        'faq.a2': 'Bien sûr. Utilisez le formulaire de contact ou appelez-nous pour discuter de votre projet.',
        'faq.q3': 'Tout est-il en stock ?',
        'faq.a3': 'Pas toujours, mais nous pouvons commander rapidement via nos fournisseurs.',
        'contact.title': 'Nous contacter',
        'contact.address1': 'Magasin SOFRACOM',
        'contact.address2': 'Rue Remada, Monastir, Tunisie',
        'contact.hours': 'Horaires : Lun–Sam, 8:00–17:00 (Fériés fermés)',
        'contact.btn': 'Demander un devis',
        'form.name': 'Nom',
        'form.email': 'E-mail',
        'form.subject': 'Objet',
        'form.message': 'Message',
        'form.send': 'Envoyer',
        'footer.quick': 'Liens rapides',
        'footer.monastir': 'Près de la Marina de Monastir & Port de pêche',
        'products.catalogBadge': 'Catalogue SOFRACOM',
        'products.catalogHeading': 'Explorez les catégories & produits',
        'products.catalogCopy': 'Parcourez les derniers antifouling, mastics, huiles, batteries et équipements livrés depuis Monastir.',
        'products.searchPlaceholder': 'Rechercher des produits…',
        'products.filters.allBrands': 'Toutes les marques',
        'products.filters.reset': 'Réinitialiser',
        'products.card.viewAction': 'Voir',
        'product.detailLabel': 'Fiche produit',
        'product.detailBreadcrumbCatalog': 'Catalogue',
        'product.detailOnOrder': 'Cet article est en commande ; la livraison prendra plus de temps.',
        'product.detailReadMore': 'Lire la suite',
        'product.detailShowLess': 'Réduire',
        'product.datasheet': 'Télécharger la fiche technique',
        'product.addToCart': 'Ajouter au panier',
        'review.sectionTitle': 'Avis clients',
        'review.sectionSubtitle': 'Ce que disent les acheteurs',
        'review.reviewsLabel': 'avis',
        'review.noReviews': 'Aucun avis pour l’instant.',
        'review.writeTitle': 'Laissez un avis',
        'review.youPurchased': 'Merci pour votre achat — partagez votre ressenti.',
        'review.onlyBuyers': 'Seuls les acheteurs vérifiés peuvent laisser un avis.',
        'review.signInToReview': 'Connectez-vous pour laisser un avis.',
        'review.ratingLabel': 'Votre note',
        'review.commentLabel': 'Retour',
        'review.commentPlaceholder': 'Parlez-nous de votre expérience avec ce produit…',
        'review.submitting': 'Envoi…',
        'review.submitReview': 'Publier l’avis',
        'review.updateReview': 'Mettre à jour l’avis',
        'review.thankYou': 'Merci pour votre retour !',
        'review.submitFailed': 'Impossible d’envoyer l’avis.',
        'review.mustPurchase': 'Vous devez avoir acheté ce produit pour laisser un avis.',
        'review.commentRequired': 'Merci d’ajouter un commentaire.',
        'cart.fabLabel': 'Panier',
        'cart.title': 'Votre commande',
        'cart.subtitle': 'Vérifiez vos articles puis confirmez vos coordonnées.',
        'cart.onOrderTitle': 'Articles sur commande',
        'cart.onOrderDescription': 'Certains articles prendront plus de temps : attendez qu’ils arrivent en stock.',
        'cart.empty': 'Votre panier est vide.',
        'cart.summary.items': 'Total des articles',
        'cart.summary.delivery': 'Frais de livraison',
        'cart.summary.grand': 'Montant total',
        'checkout.title': 'Paiement',
        'checkout.action': 'Commander',
        'checkout.savedAddressLabel': 'Adresse enregistrée',
        'checkout.enterNewAddress': 'Saisir une nouvelle adresse',
        'checkout.deliveryAddressLabel': 'Adresse de livraison',
        'checkout.notesLabel': 'Remarques (facultatif)',
        'checkout.cartEmpty': 'Le panier est vide',
        'checkout.missingInfo': 'Nom, téléphone et adresse requis.',
        'checkout.sending': 'Envoi de la commande…',
        'checkout.orderButton': 'Commander',
        'order.confirmation.delayedTitle': 'Commande reçue – délais à prévoir',
        'order.confirmation.delayedSubtitle': 'Commande enregistrée mais certains articles peuvent prendre plus de temps.',
        'order.confirmation.successTitle': 'Commande reçue',
        'order.confirmation.successSubtitle': 'Commande enregistrée avec succès.',
        'buttons.goHome': 'Retour à l’accueil',
        'checkout.signInRequired': 'Connectez-vous pour finaliser votre commande.',
        'account.label': 'Compte',
        'account.mainTitle': 'Gérez votre profil & vos commandes',
        'account.subtitle': 'Restez connectés, enregistrez vos adresses et suivez chaque achat à Monastir.',
        'account.welcomeBack': 'Heureux de vous revoir',
        'account.yourProfile': 'Votre profil',
        'account.profileSubtitle': 'Gardez vos coordonnées à jour pour accélérer le passage en caisse.',
        'account.signOut': 'Déconnexion',
        'account.savedAddresses': 'Adresses enregistrées',
        'account.orders': 'Commandes',
        'account.lastOrder': 'Dernière commande',
        'account.highlights': 'Points forts du compte',
        'account.statsTip': 'Réutilisez vos adresses et commandes enregistrées pour gagner du temps.',
        'account.defaultAddress': 'Adresse par défaut',
        'account.phoneLabel': 'Téléphone',
        'account.accountCreated': 'Compte créé',
        'account.phoneNotSaved': 'Non défini',
        'account.address': 'adresse',
        'account.addresses': 'adresses',
        'account.addressLabel': 'Libellé',
        'account.labelPlaceholder': 'ex : maison à la marina',
        'account.addressField': 'Adresse',
        'account.addressPlaceholder': 'Adresse de livraison',
        'account.saveAddress': 'Enregistrer l’adresse',
        'account.saveFirstAddress': 'Enregistrez votre première adresse pour accélérer la commande.',
        'account.addressRequired': 'Ajoutez une adresse avant de sauvegarder.',
        'account.addressSaved': 'Adresse enregistrée.',
        'account.addressSaveFailed': 'Impossible d’enregistrer l’adresse.',
        'account.addressRemoved': 'Adresse supprimée.',
        'account.addressRemoveFailed': 'Impossible de supprimer l’adresse.',
        'account.badgeDefault': 'Par défaut',
        'account.badgeSaved': 'Enregistrée',
        'account.setDefault': 'Définir par défaut',
        'account.remove': 'Supprimer',
        'account.noDefaultAddress': 'Pas encore d’adresse par défaut',
        'account.notesPrefix': 'Notes :',
        'account.orderHistory': 'Historique des commandes',
        'account.refresh': 'Actualiser',
        'account.refreshingProfile': 'Actualisation du profil…',
        'account.loadingOrders': 'Chargement des commandes…',
        'account.noOrders': 'Aucune commande pour le moment.',
        'orderStatus.new': 'Nouveau',
        'orderStatus.waiting': 'En attente',
        'orderStatus.in_progress': 'En cours',
        'orderStatus.treated': 'Traitée',
        'orderStatus.declined': 'Refusée',
        'account.itemsSingular': 'article',
        'account.itemsPlural': 'articles',
        'account.signingIn': 'Connexion en cours…',
        'account.signInSuccess': 'Connecté ! Redirection…',
        'account.signInFailed': 'Impossible de se connecter.',
        'account.returningCustomer': 'Client fidèle',
        'account.signInTitle': 'Connexion',
        'account.signInButton': 'Se connecter',
        'account.email': 'E-mail',
        'account.password': 'Mot de passe',
        'account.signUpSubtitle': 'Nouveau sur SOFRACOM',
        'account.signUpTitle': 'Créer un compte',
        'account.name': 'Nom',
        'account.phoneNumber': 'Téléphone',
        'account.signUpButton': 'Créer un compte',
        'account.passwordMinChars': 'Le mot de passe doit comporter au moins 6 caractères.',
        'account.creatingAccount': 'Création du compte…',
        'account.accountCreatedSuccess': 'Compte créé ! Bienvenue.',
        'account.signUpFailed': 'Impossible de créer le compte.',
        'account.defaultAddressUpdated': 'Adresse par défaut mise à jour.',
        'account.defaultAddressUpdateFailed': 'Impossible de mettre à jour l’adresse par défaut.',
        'orders.detailsTitle': 'Résumé de la commande',
        'orders.timelineLabel': 'Chronologie du statut',
        'orders.itemsLabel': 'Articles',
        'orders.addressLabel': 'Adresse de livraison',
        'orders.totalLabel': 'Total de la commande',
        'orders.showDetails': 'Voir le détail',
        'orders.hideDetails': 'Masquer le détail',
        'orders.noItems': 'Aucun article enregistré.',
        'orders.itemOpenProduct': 'Ouvrir le produit',
        'orders.itemLeaveReview': 'Laisser un avis',
        'orders.itemUnavailable': 'Lien produit indisponible',
    },
    ar: {
        'nav.home': 'الرئيسية',
        'nav.about': 'من نحن',
        'nav.brands': 'العلامات',
        'nav.products': 'المنتجات',
        'nav.gallery': 'المعرض',
        'nav.services': 'الخدمات',
        'nav.contact': 'اتصل بنا',
        'gallery.title': 'المعرض',
        'gallery.subtitle': 'لمحات من أعمالنا',
        'gallery.description': 'صور وفيديوهات لأحدث مشاريعنا وخدماتنا في المنستير.',
        'gallery.filterAll': 'الكل',
        'gallery.filterImages': 'صور',
        'gallery.filterVideos': 'فيديو',
        'gallery.empty': 'لا يوجد محتوى لهذا الفلتر.',
        'hero.title': 'خدمات ومستلزمات بحرية في المنستير',
        'hero.subtitle': 'إصلاحات سريعة ومشاريع كاملة: مضاد fouling، تلميع، جيلكوت، تجديد السطح، الرفع والمزيد.',
        'hero.cta1': 'استكشاف الخدمات',
        'hero.cta2': 'طلب عرض سعر',
        'about.title': 'عن SOFRACOM',
        'brands.title': 'علامات موثوقة',
        'brands.subtitle': 'نوفر أشهر العلامات البحرية ويمكننا طلب أي منتج غير متوفر بسرعة.',
        'services.title': 'الخدمات',
        'monoA.title': 'المنستير، تونس',
        'monoA.subtitle': 'إطلالات المرسى • الرباط • المدينة العتيقة',
        'monoB.title': 'حوض رفع قرب ميناء الصيد',
        'monoB.subtitle': 'على بُعد 1 ميل من مرسى المنستير',
        'testimonials.title': 'آراء الملاك',
        'faq.title': 'الأسئلة الشائعة',
        'faq.q1': 'هل توصلون إلى المرسى؟',
        'faq.a1': 'نعم، نحن قريبون ويمكننا التوصيل بسرعة إلى مرسى المنستير.',
        'faq.q2': 'هل يمكنني طلب عرض سعر مجاني؟',
        'faq.a2': 'بالتأكيد. استخدم نموذج الاتصال أدناه أو اتصل بنا لمناقشة مشروعك.',
        'faq.q3': 'هل كل ما هو معروض متوفر؟',
        'faq.a3': 'ليست كل العناصر متوفرة دائمًا، لكن يمكننا طلبها بسرعة من الموردين.',
        'contact.title': 'اتصل بنا',
        'contact.address1': 'متجر سوفراكوم',
        'contact.address2': 'شارع رمادة، المنستير',
        'contact.hours': 'الساعات: الإثنين–السبت 8:00–17:00 (عطلات مغلق)',
        'contact.btn': 'طلب عرض سعر',
        'form.name': 'الاسم',
        'form.email': 'البريد الإلكتروني',
        'form.subject': 'الموضوع',
        'form.message': 'الرسالة',
        'form.send': 'إرسال',
        'footer.quick': 'روابط سريعة',
        'footer.monastir': 'بالقرب من مرسى المنستير وميناء الصيد',
        'products.catalogBadge': 'كتالوج SOFRACOM',
        'products.catalogHeading': 'اكتشف الفئات والمنتجات',
        'products.catalogCopy': 'استعرض أحدث أنظمة المضاد للتآكل والمخاليط والزيوت والبطاريات والملحقات القادمة من المنستير.',
        'products.searchPlaceholder': 'ابحث عن المنتجات…',
        'products.filters.allBrands': 'جميع العلامات',
        'products.filters.reset': 'إعادة تعيين',
        'products.card.viewAction': 'عرض',
        'product.detailLabel': 'تفاصيل المنتج',
        'product.detailBreadcrumbCatalog': 'الكتالوج',
        'product.detailOnOrder': 'هذا العنصر قيد الطلب؛ سيستغرق التوصيل وقتاً أطول.',
        'product.detailReadMore': 'اقرأ المزيد',
        'product.detailShowLess': 'عرض أقل',
        'product.datasheet': 'تحميل الورقة الفنية',
        'product.addToCart': 'إضافة إلى السلة',
        'review.sectionTitle': 'آراء العملاء',
        'review.sectionSubtitle': 'ماذا يقول المشترون',
        'review.reviewsLabel': 'آراء',
        'review.noReviews': 'لا توجد آراء حتى الآن.',
        'review.writeTitle': 'أضف رأيك',
        'review.youPurchased': 'شكراً لشرائك — شاركنا تجربتك.',
        'review.onlyBuyers': 'فقط المشترون المؤكدون يمكنهم كتابة رأي.',
        'review.signInToReview': 'سجل دخولك لكتابة رأي.',
        'review.ratingLabel': 'تقييمك',
        'review.commentLabel': 'ملاحظات',
        'review.commentPlaceholder': 'شارك تجربتك مع هذا المنتج…',
        'review.submitting': 'جاري الإرسال…',
        'review.submitReview': 'أرسل التقييم',
        'review.updateReview': 'تحديث التقييم',
        'review.thankYou': 'شكراً على ردك!',
        'review.submitFailed': 'تعذر إرسال التقييم.',
        'review.mustPurchase': 'يجب أن تكون قد اشتريت المنتج لتقييمه.',
        'review.commentRequired': 'يرجى إضافة تعليق.',
        'cart.fabLabel': 'السلة',
        'cart.title': 'طلبك',
        'cart.subtitle': 'راجع العناصر ثم أكّد بياناتك.',
        'cart.onOrderTitle': 'عناصر بطلب مسبق',
        'cart.onOrderDescription': 'بعض العناصر تستغرق وقتاً أطول حتى تصل للمخزن.',
        'cart.empty': 'سلة التسوق فارغة.',
        'cart.summary.items': 'إجمالي المنتجات',
        'cart.summary.delivery': 'رسوم التوصيل',
        'cart.summary.grand': 'المجموع الكلي',
        'checkout.title': 'الدفع',
        'checkout.action': 'إتمام الطلب',
        'checkout.savedAddressLabel': 'عنوان محفوظ',
        'checkout.enterNewAddress': 'أدخل عنواناً جديداً',
        'checkout.deliveryAddressLabel': 'عنوان التوصيل',
        'checkout.notesLabel': 'ملاحظات (اختياري)',
        'checkout.cartEmpty': 'السلة فارغة',
        'checkout.missingInfo': 'الاسم والهاتف والعنوان مطلوبون.',
        'checkout.sending': 'جارٍ إرسال الطلب…',
        'checkout.orderButton': 'إرسال الطلب',
        'order.confirmation.delayedTitle': 'تم استلام الطلب – قد يتأخر التوصيل',
        'order.confirmation.delayedSubtitle': 'تم تسجيل الطلب لكن بعض العناصر قد تستغرق وقتاً إضافياً للوصول.',
        'order.confirmation.successTitle': 'تم استلام الطلب',
        'order.confirmation.successSubtitle': 'تم تسجيل الطلب بنجاح.',
        'buttons.goHome': 'العودة إلى الصفحة الرئيسية',
        'checkout.signInRequired': 'سجل دخولك لاستكمال الدفع.',
        'account.label': 'الحساب',
        'account.mainTitle': 'تحكّم في ملفك وطلباتك',
        'account.subtitle': 'ابقَ مسجلاً، احفظ العناوين، وتابع كل طلب من المنستير.',
        'account.welcomeBack': 'مرحباً مجدداً',
        'account.yourProfile': 'ملفك',
        'account.profileSubtitle': 'حافظ على بياناتك محدثة لتسريع خطوات الدفع.',
        'account.signOut': 'تسجيل الخروج',
        'account.savedAddresses': 'العناوين المحفوظة',
        'account.orders': 'الطلبات',
        'account.lastOrder': 'آخر طلب',
        'account.highlights': 'أبرز ملامح الحساب',
        'account.statsTip': 'استخدم العناوين والطلبات المحفوظة لإعادة الطلب بسرعة.',
        'account.defaultAddress': 'العنوان الافتراضي',
        'account.phoneLabel': 'الهاتف',
        'account.accountCreated': 'تاريخ إنشاء الحساب',
        'account.phoneNotSaved': 'غير محفوظ',
        'account.address': 'عنوان',
        'account.addresses': 'عناوين',
        'account.addressLabel': 'الوصف',
        'account.labelPlaceholder': 'مثال: منزل المرسى',
        'account.addressField': 'العنوان',
        'account.addressPlaceholder': 'عنوان التسليم',
        'account.saveAddress': 'حفظ العنوان',
        'account.saveFirstAddress': 'احفظ عنوانك الأول لتسريع الدفع.',
        'account.addressRequired': 'أضف عنواناً قبل الحفظ.',
        'account.addressSaved': 'تم حفظ العنوان.',
        'account.addressSaveFailed': 'تعذر حفظ العنوان.',
        'account.addressRemoved': 'تم حذف العنوان.',
        'account.addressRemoveFailed': 'تعذر حذف العنوان.',
        'account.badgeDefault': 'افتراضي',
        'account.badgeSaved': 'محفوظ',
        'account.setDefault': 'اجعله افتراضياً',
        'account.remove': 'إزالة',
        'account.noDefaultAddress': 'لا يوجد عنوان افتراضي بعد',
        'account.notesPrefix': 'ملاحظات:',
        'account.orderHistory': 'سجل الطلبات',
        'account.refresh': 'تحديث',
        'account.refreshingProfile': 'جارٍ تحديث الملف الشخصي…',
        'account.loadingOrders': 'جارٍ تحميل الطلبات…',
        'account.noOrders': 'لا توجد طلبات بعد.',
        'orderStatus.new': 'جديد',
        'orderStatus.waiting': 'قيد الانتظار',
        'orderStatus.in_progress': 'قيد التنفيذ',
        'orderStatus.treated': 'مكتمل',
        'orderStatus.declined': 'مرفوض',
        'account.itemsSingular': 'عنصر',
        'account.itemsPlural': 'عناصر',
        'account.signingIn': 'جاري تسجيل الدخول…',
        'account.signInSuccess': 'تم تسجيل الدخول! جاري التحويل…',
        'account.signInFailed': 'لم نتمكن من تسجيل الدخول.',
        'account.returningCustomer': 'عميل عائد',
        'account.signInTitle': 'تسجيل الدخول',
        'account.signInButton': 'دخول',
        'account.email': 'البريد الإلكتروني',
        'account.password': 'كلمة المرور',
        'account.signUpSubtitle': 'جديد في SOFRACOM',
        'account.signUpTitle': 'إنشاء حساب',
        'account.name': 'الاسم',
        'account.phoneNumber': 'رقم الهاتف',
        'account.signUpButton': 'إنشاء حساب',
        'account.passwordMinChars': 'يجب أن تكون كلمة المرور ٦ أحرف على الأقل.',
        'account.creatingAccount': 'جارٍ إنشاء الحساب…',
        'account.accountCreatedSuccess': 'تم إنشاء الحساب! أهلاً بك.',
        'account.signUpFailed': 'تعذر إنشاء الحساب.',
        'account.defaultAddressUpdated': 'تم تحديث العنوان الافتراضي.',
        'account.defaultAddressUpdateFailed': 'تعذر تحديث العنوان الافتراضي.',
        'orders.detailsTitle': 'ملخص الطلب',
        'orders.timelineLabel': 'مسار الحالة',
        'orders.itemsLabel': 'العناصر',
        'orders.addressLabel': 'عنوان التسليم',
        'orders.totalLabel': 'المجموع الكلي',
        'orders.showDetails': 'عرض التفاصيل',
        'orders.hideDetails': 'إخفاء التفاصيل',
        'orders.noItems': 'لم يتم تسجيل أي عناصر.',
        'orders.itemOpenProduct': 'فتح المنتج',
        'orders.itemLeaveReview': 'أضف تقييماً',
        'orders.itemUnavailable': 'رابط المنتج غير متاح',
    },
};

const LangContext = createContext({
    lang: 'en',
    setLang: () => {},
    t: key => TRANSLATIONS.en[key] || key,
});

const STORAGE_KEY = 'sofracom.lang.v1';

export function LangProvider({ children }) {
    const [lang, setLangState] = useState('en');

    useEffect(() => {
        const saved = typeof window !== 'undefined' ? window.localStorage.getItem(STORAGE_KEY) : null;
        if (saved && TRANSLATIONS[saved]) {
            setLangState(saved);
        }
    }, []);

    useEffect(() => {
        if (typeof window === 'undefined') return;
        window.localStorage.setItem(STORAGE_KEY, lang);
        document.documentElement.lang = lang;
        document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
        document.body.classList.toggle('rtl', lang === 'ar');
    }, [lang]);

    const value = useMemo(() => {
        const translator = key => {
            return TRANSLATIONS[lang]?.[key] || TRANSLATIONS.en[key] || key;
        };
        return {
            lang,
            setLang: newLang => {
                if (TRANSLATIONS[newLang]) {
                    setLangState(newLang);
                }
            },
            t: translator,
        };
    }, [lang]);

    return <LangContext.Provider value={value}>{children}</LangContext.Provider>;
}

export function useLang() {
    return useContext(LangContext);
}
