import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const TRANSLATIONS = {
    en: {
        'nav.home': 'Home',
        'nav.about': 'About',
        'nav.brands': 'Brands',
        'nav.products': 'Products',
        'nav.gallery': 'Gallery',
        'nav.services': 'Services',
        'nav.contact': 'Contact',
        'gallery.title': 'Gallery',
        'gallery.subtitle': 'Work snapshots from Monastir',
        'gallery.description': 'Images and videos documenting our latest refits, coatings, and marina services.',
        'gallery.filterAll': 'All',
        'gallery.filterImages': 'Images',
        'gallery.filterVideos': 'Videos',
        'gallery.empty': 'No gallery entries match that filter.',
        'hero.title': 'Marine Supplies & Services in Monastir',
        'hero.subtitle': 'Quick repairs and full projects: antifouling, polishing, gelcoat, deck renewal, hauling & more.',
        'hero.cta1': 'Explore Services',
        'hero.cta2': 'Get a Quote',
        'about.title': 'About SOFRACOM',
        'brands.title': 'Trusted Brands',
        'brands.subtitle': 'We stock leading marine brands and can quickly order what’s not on-hand via established suppliers.',
        'services.title': 'Services',
        'monoA.title': 'Monastir, Tunisia',
        'monoA.subtitle': 'Marina views • Ribat • Old town',
        'monoB.title': 'Haul-out near Port de pêche',
        'monoB.subtitle': '1 mile from Monastir Marina',
        'testimonials.title': 'What skippers say',
        'faq.title': 'FAQ',
        'faq.q1': 'Do you deliver to the marina?',
        'faq.a1': 'Yes, we’re nearby and can arrange quick deliveries to Marina Monastir.',
        'faq.q2': 'Can I request a free quote?',
        'faq.a2': 'Absolutely. Use the contact form below or call us to discuss your project.',
        'faq.q3': 'Do you stock everything shown?',
        'faq.a3': 'Not all items are in stock at all times, but we can order quickly via suppliers.',
        'contact.title': 'Contact Us',
        'contact.address1': 'SOFRACOM Store',
        'contact.address2': 'Remada Street, Monastir, Tunisia',
        'contact.hours': 'Hours: Mon–Sat, 8:00–17:00 (Closed public holidays)',
        'contact.btn': 'Request a Free Quote',
        'form.name': 'Name',
        'form.email': 'Email',
        'form.subject': 'Subject',
        'form.message': 'Message',
        'form.send': 'Send',
        'footer.quick': 'Quick Links',
        'footer.monastir': 'Near Marina Monastir & Port de pêche',
        'account.label': 'Account',
        'account.mainTitle': 'Manage your profile & orders',
        'account.subtitle': 'Stay signed in, save addresses, and track every purchase from Monastir.',
        'account.welcomeBack': 'Welcome back',
        'account.yourProfile': 'Your profile',
        'account.signOut': 'Sign out',
        'account.savedAddresses': 'Saved addresses',
        'account.orders': 'Orders',
        'account.lastOrder': 'Last order',
        'account.highlights': 'Account highlights',
        'account.defaultAddress': 'Default address',
        'account.phoneLabel': 'Phone',
        'account.accountCreated': 'Account created',
        'account.phoneNotSaved': 'Not saved',
        'account.address': 'address',
        'account.addresses': 'addresses',
        'account.addressLabel': 'Label',
        'account.labelPlaceholder': 'e.g., Marina home',
        'account.addressField': 'Address',
        'account.addressPlaceholder': 'Delivery address',
        'account.saveAddress': 'Save address',
        'account.saveFirstAddress': 'Save your first address to speed up checkout.',
        'account.addressRequired': 'Add an address before saving.',
        'account.addressSaved': 'Address saved.',
        'account.addressSaveFailed': 'Unable to save address.',
        'account.addressRemoved': 'Address removed.',
        'account.addressRemoveFailed': 'Unable to remove address.',
        'account.badgeDefault': 'Default',
        'account.badgeSaved': 'Saved',
        'account.setDefault': 'Set default',
        'account.remove': 'Remove',
        'account.noDefaultAddress': 'No default yet',
        'account.notesPrefix': 'Notes:',
        'account.orderHistory': 'Order history',
        'account.refresh': 'Refresh',
        'account.loadingOrders': 'Loading orders…',
        'account.noOrders': 'No orders yet.',
        'orderStatus.new': 'New',
        'orderStatus.waiting': 'Waiting',
        'orderStatus.in_progress': 'In progress',
        'orderStatus.treated': 'Treated',
        'orderStatus.declined': 'Declined',
        'account.itemsSingular': 'item',
        'account.itemsPlural': 'items',
        'account.signingIn': 'Signing in…',
        'account.signInSuccess': 'Signed in! Redirecting…',
        'account.signInFailed': 'Unable to sign in.',
        'account.returningCustomer': 'Returning customer',
        'account.signInTitle': 'Sign in',
        'account.signInButton': 'Sign in',
        'account.email': 'Email',
        'account.password': 'Password',
        'account.signUpSubtitle': 'New to SOFRACOM',
        'account.signUpTitle': 'Create an account',
        'account.name': 'Name',
        'account.phoneNumber': 'Phone',
        'account.signUpButton': 'Create account',
        'account.passwordMinChars': 'Password must be at least 6 characters.',
        'account.creatingAccount': 'Creating account…',
        'account.accountCreatedSuccess': 'Account created. Welcome!',
        'account.signUpFailed': 'Unable to create account.',
        'account.defaultAddressUpdated': 'Default address updated.',
        'account.defaultAddressUpdateFailed': 'Unable to update default address.',
    },
    fr: {
        'nav.home': 'Accueil',
        'nav.about': 'À propos',
        'nav.brands': 'Marques',
        'nav.products': 'Produits',
        'nav.gallery': 'Galerie',
        'nav.services': 'Services',
        'nav.contact': 'Contact',
        'gallery.title': 'Galerie',
        'gallery.subtitle': 'Instants de nos travaux',
        'gallery.description': 'Images et vidéos des derniers chantiers, peintures et interventions à Monastir.',
        'gallery.filterAll': 'Tous',
        'gallery.filterImages': 'Images',
        'gallery.filterVideos': 'Vidéos',
        'gallery.empty': 'Aucun contenu disponible pour ce filtre.',
        'hero.title': 'Fournitures et services marins à Monastir',
        'hero.subtitle': 'Petites réparations et projets complets : antifouling, polissage, gelcoat, pont, carénage et plus.',
        'hero.cta1': 'Découvrir les services',
        'hero.cta2': 'Demander un devis',
        'about.title': 'À propos de SOFRACOM',
        'brands.title': 'Marques de confiance',
        'brands.subtitle': 'Nous stockons des marques marines leaders et pouvons commander rapidement ce qui manque.',
        'services.title': 'Services',
        'monoA.title': 'Monastir, Tunisie',
        'monoA.subtitle': 'Vue marina • Ribat • Médina',
        'monoB.title': 'Carénage près du Port de pêche',
        'monoB.subtitle': 'À 1 mile de la Marina de Monastir',
        'testimonials.title': 'Avis de skippers',
        'faq.title': 'FAQ',
        'faq.q1': 'Livrez-vous à la marina ?',
        'faq.a1': 'Oui, nous sommes proches et pouvons livrer rapidement à la Marina de Monastir.',
        'faq.q2': 'Puis-je demander un devis gratuit ?',
        'faq.a2': 'Bien sûr. Utilisez le formulaire de contact ou appelez-nous pour discuter de votre projet.',
        'faq.q3': 'Tout est-il en stock ?',
        'faq.a3': 'Pas toujours, mais nous pouvons commander rapidement via nos fournisseurs.',
        'contact.title': 'Nous contacter',
        'contact.address1': 'Magasin SOFRACOM',
        'contact.address2': 'Rue Remada, Monastir, Tunisie',
        'contact.hours': 'Horaires : Lun–Sam, 8:00–17:00 (Fériés fermés)',
        'contact.btn': 'Demander un devis',
        'form.name': 'Nom',
        'form.email': 'E-mail',
        'form.subject': 'Objet',
        'form.message': 'Message',
        'form.send': 'Envoyer',
        'footer.quick': 'Liens rapides',
        'footer.monastir': 'Près de la Marina de Monastir & Port de pêche',
        'account.label': 'Compte',
        'account.mainTitle': 'Gérez votre profil & vos commandes',
        'account.subtitle': 'Restez connectés, enregistrez vos adresses et suivez chaque achat à Monastir.',
        'account.welcomeBack': 'Heureux de vous revoir',
        'account.yourProfile': 'Votre profil',
        'account.signOut': 'Déconnexion',
        'account.savedAddresses': 'Adresses enregistrées',
        'account.orders': 'Commandes',
        'account.lastOrder': 'Dernière commande',
        'account.highlights': 'Points forts du compte',
        'account.defaultAddress': 'Adresse par défaut',
        'account.phoneLabel': 'Téléphone',
        'account.accountCreated': 'Compte créé',
        'account.phoneNotSaved': 'Non défini',
        'account.address': 'adresse',
        'account.addresses': 'adresses',
        'account.addressLabel': 'Libellé',
        'account.labelPlaceholder': 'ex : maison à la marina',
        'account.addressField': 'Adresse',
        'account.addressPlaceholder': 'Adresse de livraison',
        'account.saveAddress': 'Enregistrer l’adresse',
        'account.saveFirstAddress': 'Enregistrez votre première adresse pour accélérer la commande.',
        'account.addressRequired': 'Ajoutez une adresse avant de sauvegarder.',
        'account.addressSaved': 'Adresse enregistrée.',
        'account.addressSaveFailed': 'Impossible d’enregistrer l’adresse.',
        'account.addressRemoved': 'Adresse supprimée.',
        'account.addressRemoveFailed': 'Impossible de supprimer l’adresse.',
        'account.badgeDefault': 'Par défaut',
        'account.badgeSaved': 'Enregistrée',
        'account.setDefault': 'Définir par défaut',
        'account.remove': 'Supprimer',
        'account.noDefaultAddress': 'Pas encore d’adresse par défaut',
        'account.notesPrefix': 'Notes :',
        'account.orderHistory': 'Historique des commandes',
        'account.refresh': 'Actualiser',
        'account.loadingOrders': 'Chargement des commandes…',
        'account.noOrders': 'Aucune commande pour le moment.',
        'orderStatus.new': 'Nouveau',
        'orderStatus.waiting': 'En attente',
        'orderStatus.in_progress': 'En cours',
        'orderStatus.treated': 'Traitée',
        'orderStatus.declined': 'Refusée',
        'account.itemsSingular': 'article',
        'account.itemsPlural': 'articles',
        'account.signingIn': 'Connexion en cours…',
        'account.signInSuccess': 'Connecté ! Redirection…',
        'account.signInFailed': 'Impossible de se connecter.',
        'account.returningCustomer': 'Client fidèle',
        'account.signInTitle': 'Connexion',
        'account.signInButton': 'Se connecter',
        'account.email': 'E-mail',
        'account.password': 'Mot de passe',
        'account.signUpSubtitle': 'Nouveau sur SOFRACOM',
        'account.signUpTitle': 'Créer un compte',
        'account.name': 'Nom',
        'account.phoneNumber': 'Téléphone',
        'account.signUpButton': 'Créer un compte',
        'account.passwordMinChars': 'Le mot de passe doit comporter au moins 6 caractères.',
        'account.creatingAccount': 'Création du compte…',
        'account.accountCreatedSuccess': 'Compte créé ! Bienvenue.',
        'account.signUpFailed': 'Impossible de créer le compte.',
        'account.defaultAddressUpdated': 'Adresse par défaut mise à jour.',
        'account.defaultAddressUpdateFailed': 'Impossible de mettre à jour l’adresse par défaut.',
    },
    ar: {
        'nav.home': 'الرئيسية',
        'nav.about': 'من نحن',
        'nav.brands': 'العلامات',
        'nav.products': 'المنتجات',
        'nav.gallery': 'المعرض',
        'nav.services': 'الخدمات',
        'nav.contact': 'اتصل بنا',
        'gallery.title': 'المعرض',
        'gallery.subtitle': 'لمحات من أعمالنا',
        'gallery.description': 'صور وفيديوهات لأحدث مشاريعنا وخدماتنا في المنستير.',
        'gallery.filterAll': 'الكل',
        'gallery.filterImages': 'صور',
        'gallery.filterVideos': 'فيديو',
        'gallery.empty': 'لا يوجد محتوى لهذا الفلتر.',
        'hero.title': 'خدمات ومستلزمات بحرية في المنستير',
        'hero.subtitle': 'إصلاحات سريعة ومشاريع كاملة: مضاد fouling، تلميع، جيلكوت، تجديد السطح، الرفع والمزيد.',
        'hero.cta1': 'استكشاف الخدمات',
        'hero.cta2': 'طلب عرض سعر',
        'about.title': 'عن SOFRACOM',
        'brands.title': 'علامات موثوقة',
        'brands.subtitle': 'نوفر أشهر العلامات البحرية ويمكننا طلب أي منتج غير متوفر بسرعة.',
        'services.title': 'الخدمات',
        'monoA.title': 'المنستير، تونس',
        'monoA.subtitle': 'إطلالات المرسى • الرباط • المدينة العتيقة',
        'monoB.title': 'حوض رفع قرب ميناء الصيد',
        'monoB.subtitle': 'على بُعد 1 ميل من مرسى المنستير',
        'testimonials.title': 'آراء الملاك',
        'faq.title': 'الأسئلة الشائعة',
        'faq.q1': 'هل توصلون إلى المرسى؟',
        'faq.a1': 'نعم، نحن قريبون ويمكننا التوصيل بسرعة إلى مرسى المنستير.',
        'faq.q2': 'هل يمكنني طلب عرض سعر مجاني؟',
        'faq.a2': 'بالتأكيد. استخدم نموذج الاتصال أدناه أو اتصل بنا لمناقشة مشروعك.',
        'faq.q3': 'هل كل ما هو معروض متوفر؟',
        'faq.a3': 'ليست كل العناصر متوفرة دائمًا، لكن يمكننا طلبها بسرعة من الموردين.',
        'contact.title': 'اتصل بنا',
        'contact.address1': 'متجر سوفراكوم',
        'contact.address2': 'شارع رمادة، المنستير',
        'contact.hours': 'الساعات: الإثنين–السبت 8:00–17:00 (عطلات مغلق)',
        'contact.btn': 'طلب عرض سعر',
        'form.name': 'الاسم',
        'form.email': 'البريد الإلكتروني',
        'form.subject': 'الموضوع',
        'form.message': 'الرسالة',
        'form.send': 'إرسال',
        'footer.quick': 'روابط سريعة',
        'footer.monastir': 'بالقرب من مرسى المنستير وميناء الصيد',
        'account.label': 'الحساب',
        'account.mainTitle': 'تحكّم في ملفك وطلباتك',
        'account.subtitle': 'ابقَ مسجلاً، احفظ العناوين، وتابع كل طلب من المنستير.',
        'account.welcomeBack': 'مرحباً مجدداً',
        'account.yourProfile': 'ملفك',
        'account.signOut': 'تسجيل الخروج',
        'account.savedAddresses': 'العناوين المحفوظة',
        'account.orders': 'الطلبات',
        'account.lastOrder': 'آخر طلب',
        'account.highlights': 'أبرز ملامح الحساب',
        'account.defaultAddress': 'العنوان الافتراضي',
        'account.phoneLabel': 'الهاتف',
        'account.accountCreated': 'تاريخ إنشاء الحساب',
        'account.phoneNotSaved': 'غير محفوظ',
        'account.address': 'عنوان',
        'account.addresses': 'عناوين',
        'account.addressLabel': 'الوصف',
        'account.labelPlaceholder': 'مثال: منزل المرسى',
        'account.addressField': 'العنوان',
        'account.addressPlaceholder': 'عنوان التسليم',
        'account.saveAddress': 'حفظ العنوان',
        'account.saveFirstAddress': 'احفظ عنوانك الأول لتسريع الدفع.',
        'account.addressRequired': 'أضف عنواناً قبل الحفظ.',
        'account.addressSaved': 'تم حفظ العنوان.',
        'account.addressSaveFailed': 'تعذر حفظ العنوان.',
        'account.addressRemoved': 'تم حذف العنوان.',
        'account.addressRemoveFailed': 'تعذر حذف العنوان.',
        'account.badgeDefault': 'افتراضي',
        'account.badgeSaved': 'محفوظ',
        'account.setDefault': 'اجعله افتراضياً',
        'account.remove': 'إزالة',
        'account.noDefaultAddress': 'لا يوجد عنوان افتراضي بعد',
        'account.notesPrefix': 'ملاحظات:',
        'account.orderHistory': 'سجل الطلبات',
        'account.refresh': 'تحديث',
        'account.loadingOrders': 'جارٍ تحميل الطلبات…',
        'account.noOrders': 'لا توجد طلبات بعد.',
        'orderStatus.new': 'جديد',
        'orderStatus.waiting': 'قيد الانتظار',
        'orderStatus.in_progress': 'قيد التنفيذ',
        'orderStatus.treated': 'مكتمل',
        'orderStatus.declined': 'مرفوض',
        'account.itemsSingular': 'عنصر',
        'account.itemsPlural': 'عناصر',
        'account.signingIn': 'جاري تسجيل الدخول…',
        'account.signInSuccess': 'تم تسجيل الدخول! جاري التحويل…',
        'account.signInFailed': 'لم نتمكن من تسجيل الدخول.',
        'account.returningCustomer': 'عميل عائد',
        'account.signInTitle': 'تسجيل الدخول',
        'account.signInButton': 'دخول',
        'account.email': 'البريد الإلكتروني',
        'account.password': 'كلمة المرور',
        'account.signUpSubtitle': 'جديد في SOFRACOM',
        'account.signUpTitle': 'إنشاء حساب',
        'account.name': 'الاسم',
        'account.phoneNumber': 'رقم الهاتف',
        'account.signUpButton': 'إنشاء حساب',
        'account.passwordMinChars': 'يجب أن تكون كلمة المرور ٦ أحرف على الأقل.',
        'account.creatingAccount': 'جارٍ إنشاء الحساب…',
        'account.accountCreatedSuccess': 'تم إنشاء الحساب! أهلاً بك.',
        'account.signUpFailed': 'تعذر إنشاء الحساب.',
        'account.defaultAddressUpdated': 'تم تحديث العنوان الافتراضي.',
        'account.defaultAddressUpdateFailed': 'تعذر تحديث العنوان الافتراضي.',
    },
};

const LangContext = createContext({
    lang: 'en',
    setLang: () => {},
    t: key => TRANSLATIONS.en[key] || key,
});

const STORAGE_KEY = 'sofracom.lang.v1';

export function LangProvider({ children }) {
    const [lang, setLangState] = useState('en');

    useEffect(() => {
        const saved = typeof window !== 'undefined' ? window.localStorage.getItem(STORAGE_KEY) : null;
        if (saved && TRANSLATIONS[saved]) {
            setLangState(saved);
        }
    }, []);

    useEffect(() => {
        if (typeof window === 'undefined') return;
        window.localStorage.setItem(STORAGE_KEY, lang);
        document.documentElement.lang = lang;
        document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
        document.body.classList.toggle('rtl', lang === 'ar');
    }, [lang]);

    const value = useMemo(() => {
        const translator = key => {
            return TRANSLATIONS[lang]?.[key] || TRANSLATIONS.en[key] || key;
        };
        return {
            lang,
            setLang: newLang => {
                if (TRANSLATIONS[newLang]) {
                    setLangState(newLang);
                }
            },
            t: translator,
        };
    }, [lang]);

    return <LangContext.Provider value={value}>{children}</LangContext.Provider>;
}

export function useLang() {
    return useContext(LangContext);
}
